import Genl.Curves.BelyiDescent
import Genl.Curves.Covering
import Genl.Curves.ProofPackage
import Genl.Curves.Theory
import Genl.GeneralPosition.HeightTheory
import Genl.GeneralPosition.ProofPackage
import Genl.GeneralPosition.TheoremTwoOne
import Genl.Mathlib.NumberTheory.ArithmeticDivisor
import Genl.Mathlib.Order.BoundedDiscrepancy
