/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LANA Project
-/
import Verso
import VersoManual
import VersoBlueprint
import Genl

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Generalities on Heights" =>

This chapter tracks §1 of the paper: arithmetic line bundles, arithmetic divisors,
height functions and their classes up to bounded discrepancy, log-differents and
log-conductors. The elementary combinatorial layer (BD-classes, arithmetic divisors and
their degrees) is formalised in `Genl/Mathlib/` and is intended for eventual inclusion in
Mathlib; the geometric layer (arithmetic line bundles on normal, `ℤ`-proper, `ℤ`-flat
models and the associated heights) is future work.

:::definition "arithmetic_line_bundle"
(Definition 1.1) For a normal scheme $`X` which is proper and flat over $`\mathrm{Spec}\,ℤ`,
an *arithmetic line bundle* $`\overline{\mathcal{L}} = (\mathcal{L}, |-|_{\mathcal{L}})` on
$`X` is a line bundle $`\mathcal{L}` on $`X` together with a Hermitian metric on the
associated line bundle on the complex analytic space $`X^{\mathrm{arc}}`, compatible with
complex conjugation. Isomorphism classes form a group $`\mathrm{APic}(X)`.
:::

:::definition "arithmetic_divisor" (lean := "NumberField.ArithmeticDivisor")
(§1) For a number field $`F`, an *arithmetic divisor* is a finite formal sum
$`\sum_v c_v \cdot v` over the valuations of $`F`, with $`c_v ∈ ℤ` at the nonarchimedean
and $`c_v ∈ ℝ` at the archimedean valuations. Arithmetic divisors form a group
$`\mathrm{ADiv}(F)`, and principal arithmetic divisors a subgroup
$`\mathrm{APrc}(F) ⊆ \mathrm{ADiv}(F)` with
$`\mathrm{ADiv}(F)/\mathrm{APrc}(F) \cong \mathrm{APic}(\mathrm{Spec}\,\mathcal{O}_F)`.
:::

:::definition "degree_arithmetic_divisor" (lean := "NumberField.ArithmeticDivisor.degree")
(§1) The *degree* map $`\deg_F : \mathrm{ADiv}(F) → ℝ` sends a nonarchimedean valuation
$`v` to $`\log q_v`, where $`q_v` is the cardinality of the residue field at $`v`, and an
archimedean valuation to $`1`. It kills {uses "arithmetic_divisor"}[principal divisors]
and its normalisation $`\underline{\deg}_F := \deg_F / [F : ℚ]` is invariant under base
change to finite extensions of $`F`.
:::

:::definition "height_function"
(Definition 1.2 (i)) For an arithmetic line bundle
$`\overline{\mathcal{M}}` on a normal, $`ℤ`-proper, $`ℤ`-flat scheme $`X`, the associated
*height function* $`\mathrm{ht}_{\overline{\mathcal{M}}} : X(\overline{ℚ}) → ℝ` is
defined by $`\mathrm{ht}_{\overline{\mathcal{M}}}(x) =
\underline{\deg}_F(x_F^* \overline{\mathcal{M}})` via pull back along the morphism
$`x_F : \mathrm{Spec}\,\mathcal{O}_F → X` determined by $`x`. This uses
{uses "arithmetic_line_bundle"}[] and {uses "degree_arithmetic_divisor"}[].
:::

:::definition "bd_class" (lean := "DiscrepancyLE")
(Definition 1.2 (ii)) For real valued functions $`α, β` on a set $`\mathcal{F}`, write
$`α \lesssim β` if there is a constant $`C ∈ ℝ` with $`α(x) ≤ β(x) + C` for all
$`x ∈ \mathcal{F}`, and $`α \approx β` if both $`α \lesssim β` and $`β \lesssim α`. The
equivalence classes of $`\approx` are the *BD-classes* ("bounded discrepancy classes").
:::

:::definition "points_of_bounded_degree"
(Example 1.3 (i)) For $`d ∈ ℕ ∪ \{∞\}` one writes
$`X(\overline{ℚ})^{≤d} ⊆ X(\overline{ℚ})` for the union of the subsets $`X(F)` as $`F`
ranges over the number fields of degree $`≤ d` over $`ℚ`, and
$`X(\overline{ℚ})^{=d} := X(\overline{ℚ})^{≤d} \setminus X(\overline{ℚ})^{≤d-1}`.
:::

:::definition "compactly_bounded_subset"
(Example 1.3 (ii)) For a finite set $`V` of valuations of $`ℚ` containing the archimedean
one and a choice of Galois stable compact domains $`\mathcal{K}_v` in the local points at
each $`v ∈ V`, the associated *compactly bounded subset*
$`\mathcal{K}_V ⊆ X(\overline{ℚ})` is the set of points whose Galois conjugates lie in
$`\mathcal{K}_v` at each $`v ∈ V`. Its *support* $`V` and its *bounding domains*
$`\mathcal{K}_v` are completely determined by the subset $`\mathcal{K}_V`.
:::

:::proposition "heights_basic_properties"
(Proposition 1.4) Heights are additive in the arithmetic line bundle; heights associated
to arithmetic line bundles whose generic fibre is generated by global sections are bounded
below (on any subset); the BD-class of $`\mathrm{ht}_{\overline{\mathcal{L}}}` depends
only on the isomorphism class of the generic fibre $`\mathcal{L}_ℚ`; and for ample
$`\mathcal{L}_ℚ` and $`C ∈ ℝ`, the set of points of
{uses "points_of_bounded_degree"}[bounded degree] with
$`\mathrm{ht}_{\overline{\mathcal{L}}} ≤ C` is finite. Uses {uses "height_function"}[]
and {uses "bd_class"}[].
:::

:::definition "log_diff"
(Definition 1.5 (i), (iii)) Every $`x ∈ X(\overline{ℚ})` of a normal, $`ℤ`-proper,
$`ℤ`-flat $`X` has a well defined *minimal field of definition* $`F_x ⊆ \overline{ℚ}`;
the different ideal of $`F_x` determines an effective arithmetic divisor
$`δ_x ∈ \mathrm{ADiv}(F_x)` and the *log-different function*
$`\text{log-diff}_X(x) := \underline{\deg}_{F_x}(δ_x)`. Uses
{uses "arithmetic_divisor"}[] and {uses "degree_arithmetic_divisor"}[].
:::

:::definition "log_cond"
(Definition 1.5 (ii), (iv)) For an effective Cartier divisor $`D ⊆ X` with
$`U_X = X \setminus D` and a point $`x ∈ U_X(F) ⊆ U_X(\overline{ℚ})` with $`F` a minimal
field of definition, pulling back $`D` along $`x` and passing to the reduced subscheme
yields the *conductor* $`\mathfrak{f}^D_x ∈ \mathrm{ADiv}(F)` and the
*log-conductor function*
$`\text{log-cond}_D(x) := \underline{\deg}_F(\mathfrak{f}^D_x)`. Uses
{uses "arithmetic_divisor"}[], {uses "degree_arithmetic_divisor"}[] and
{uses "log_diff"}[].
:::

:::proposition "conductor_bounded_by_height"
(Proposition 1.6) For an effective Cartier divisor $`D ⊆ X` and an arithmetic line bundle
$`\overline{\mathcal{L}}` with $`\mathcal{L} = \mathcal{O}_X(D)`, one has
$`\text{log-cond}_D \lesssim \mathrm{ht}_D` on $`U_X(\overline{ℚ})`. Uses
{uses "log_cond"}[], {uses "height_function"}[] and {uses "bd_class"}[].
:::

:::proof "conductor_bounded_by_height"
At the nonarchimedean primes this is immediate from the definition of the log-conductor;
at the archimedean primes one uses that the metric of $`\overline{\mathcal{L}}` is
bounded on the compact space $`X^{\mathrm{arc}}`.
:::

:::proposition "conductors_and_log_differents"
(Proposition 1.7) For a generically finite morphism $`φ : Y → Z` of normal, $`ℤ`-proper,
$`ℤ`-flat schemes of dimension two and compatible divisors $`D ⊆ Y`, $`E ⊆ Z` with
$`(U_Y)_ℚ → (U_Z)_ℚ` finite étale of ramification indices dividing $`e`:
(i) $`\text{log-cond}_E - \text{log-cond}_D \lesssim \text{log-diff}_Y - \text{log-diff}_Z
\lesssim (1 - e^{-1}) \cdot \text{log-cond}_E` on $`U_Y(\overline{ℚ})`;
(ii) if all ramification indices equal $`e`, then
$`\deg(ω_{Y_ℚ}) = \deg(ω_{Z_ℚ}(E_ℚ))|_{Y_ℚ} \{1 - \deg(\mathcal{O}(E))/(e \cdot \deg(ω(E)))\}`.
Uses {uses "log_diff"}[], {uses "log_cond"}[] and {uses "bd_class"}[].
:::

:::proof "conductors_and_log_differents"
Over a suitable open $`\mathrm{Spec}\,ℤ[Σ^{-1}]` the morphism is a tamely ramified
covering of smooth proper families of curves, where the statement follows from the
elementary theory of differents; the finitely many remaining primes contribute bounded
discrepancies by an elementary estimate for differents of extensions of local fields of
bounded degree. Part (ii) is the Riemann–Hurwitz formula.
:::
